### ISSUE TITLE
License discrepancy

### ISSUE THREAD

**Issue by fntlnz** [stakhanovist/queue#13]
From `composer.json`

```
"license": "BSD-3-Clause",
```

From any `*.php` file

```
 * @license     http://opensource.org/licenses/BSD-2-Clause Simplified BSD License
```

The `LICENSE` file in the project root is a `BSD 2 clause` so why the composer json is not reporting that? Is because the original creator license was a 3 clause? 

It would not be enough to have the original license in the project root as has been done?

**Comment by leodido** [comment]
I locally fixed composer. I'll push changes soon.
