### ISSUE TITLE
Adapters organization

### ISSUE THREAD

**Issue by fntlnz** [stakhanovist/queue#5]
I really like the idea that there's an adapters package where there are a number of adapters along with  interfaces and capabilities related to them.

BTW there are a few things I don't understand about this package:
- Why there's a Db directory containing sql files? IMO  this is not the right place where to put them.
- Why there's a Mongo package with just an abstract class when the latter concrete implementations are under the Adapter package? 

By the way seems strange to me that in the same package (Adapter) there are two directories (Db and Mongo) that one might think contain specific adapters that requires a sub-folder for reasons of clarity and in the end in the first we find some sql files and in the other a single abstract class.

What do you think?

**Comment by leogr** [comment]
I agree with you.

Some conventions derive from the old implementation and should be improved. 
Furthermore, the `queue` package should not have adapters in bundle (except for the array adapter and the null adapter, because their special purpose). Each adapter should resides in its own package (ie. queue-db, queue-mongo, etc).

Would you like to refactor them?

**Comment by fntlnz** [comment]
Along with #10 this can be a good starting point for a refactoring. I add the refactoring badge and I'll try to work on these in the next few days.

**Comment by leogr** [comment]
Furthermore the Null adapter should be renamed (to avoid PHP reserved word)

**Comment by fntlnz** [comment]
Ok, what do you think about `NullAdapter` ? 
For the moment I added PHP 7 to the travis allowed failures build matrix in `develop` so we can track other php 7 compatibility issues.

https://travis-ci.org/stakhanovist/queue/jobs/72790621
https://github.com/stakhanovist/queue/commit/bb2b09b163b400cd2852bb9a14d682992de17055

**Comment by leogr** [comment]
Other adapters do not have the "Adapter" suffix, BTW it could be ok.

**Comment by fntlnz** [comment]
What about ArrayAdapter?

**Comment by leogr** [comment]
It's the same issue, we could choose to suffix all adapters.
@leodido what do you think about?

**Comment by leodido** [comment]
Hi guys,
it's ok for me to preprend all adapters with the "type" they handle - e.g., **NullAdapter**, **ArrayAdapter**.

Except generic adapters, the specific ones MUST have its own package/library.

**Comment by leodido** [comment]
FYI, I have just pushed [queue-mongodb](https://github.com/stakhanovist/queue-mongodb). One less thing.
