### ISSUE TITLE
Amazon SQS adapter

### ISSUE THREAD

**Issue by fntlnz** [stakhanovist/queue#9]
SQS is a saas by Amazon that provides a queue backend.

Information about SQS:
http://aws.amazon.com/documentation/sqs/

**Comment by leogr** [comment]
There's a ZF implementations [here](https://github.com/zendframework/ZendService_Amazon/tree/master/library/ZendService/Amazon/Sqs) that can be useful for that.

**Comment by fntlnz** [comment]
The [Amazon PHP SDK](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-sqs.html) have a full API for SQS, I think this is the way to go for two reasons:
- As it is written by them it **should** always be updated
- The ZF implementation is pretty old and not touched since 2013.

I'm not saying that the ZF implementation does not work, just that I consider most reliable the one written by Amazon.

What do you think?

**Comment by leodido** [comment]
I agree with @fntlnz.

**Comment by leogr** [comment]
:+1:

**Comment by fntlnz** [comment]
This is a wip in https://github.com/stakhanovist/queue-amazon-sqs
We can close here.
